### ISSUE TITLE
"Resource temporarily unavailable" for PersistentCache

### ISSUE THREAD

**Issue by rui-scio** [mariushelf/shelved_cache#1]
When I run the following code twice, I get `Resource temporarily unavailable` on the second run.
```
@cachetools.cached(PersistentCache(LRUCache, 'mycache', maxsize=2))
def square(x):
    print("called")
    return x * x

assert square(3) == 9
# outputs "called"
assert square(3) == 9
# no output because the cache is used
```

As a comparison, I can run the following code using just `LRUCache` multiple times without a problem. 
```
@cached(cache=LRUCache(maxsize=3))
def square(x):
    print("called")
    return x * x

assert square(3) == 9
# outputs "called"
assert square(3) == 9
# no output because the cache is used
```

Is this a bug in `PersistentCache`?

**Comment by mariushelf** [comment]
If you run the code twice in one script, then the same file will be used for 2 caches. 
For the second function, you need to specify a different filename.
